spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

logging:
  path: ${L_PATH:logs}
  file: ${spring.application.name}-${current.date}
  config: 'classpath:log.xml'
  level:
    com.jay.*: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix.shareSecurityContext: true

feign.hystrix.enabled: false

health.config.enabled: false

management.security.enabled: false

---

spring:
  profiles: docker

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
