server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: docker

eureka:
  instance:
    prefer-ip-address: false
    hostname: registry
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
